<a href="https://colab.research.google.com/github/KjelleJ/enkla-ai-experiment/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Indentering

In [ ]:
# indentering både i funktionsdefinitionen och i loopen

def simple(start, stop):
    for i in range(start, stop):
        print(i)

# funktionsanrop
simple(1, 5)

1
2
3
4


# Några datatyper

## List - här används hak-parenteser []

In [ ]:
# elementen i listan kan vara av olika datatyper och också blandat
lista = [1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
type(lista)

list

In [ ]:
# index startar från 0 - så första elementet är...
lista[0]

1

In [ ]:
# kan oxå indexeras bakifrån
lista[-1]

8

In [ ]:
# listor kan ändras
lista[0] = 22
print(lista)

[22, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# listor kan ändras
lista[1] = [9, 10]
print(lista)

[22, [9, 10], 3, 4, 5, 6, 7, 8]


In [ ]:
# listor kan ändras
lista[2] = "tre"
print(lista)

[22, [9, 10], 'tre', 4, 5, 6, 7, 8]


## Dictionary - här används krull-parenteser {}

In [ ]:
# definieras med nyckel:värde eller key:value
dict = {1:"ett", 2:"två", "tre":3}
print(dict)

{1: 'ett', 2: 'två', 'tre': 3}


In [ ]:
type(dict)

dict

In [ ]:
# key 1
dict[1]

'ett'

In [ ]:
# key 'tre'
dict['tre']

3

In [ ]:
dict[1] = "första"
print(dict)

{1: 'första', 2: 'två', 'tre': 3}


# if-elif-else

In [ ]:
x = 10
if x < 10:
    print("x < 10")
elif x > 10:
    print("x > 10")
else:
    print("x = 10")

x = 10


# while loop

In [ ]:
i = 1
while i < 5:
    print(i)
    # OBS i++ ej möjligt i Python
    i = i + 1

1
2
3
4


# for loop

In [ ]:
for i in range(1, 5):
    print(i)

1
2
3
4


In [ ]:
lista = [0, "ett", 2, "tre"]
for x in lista:
    print(x)

0
ett
2
tre


# NumPy
Python saknar datastrukturen array. Bl.a. därför används Python-biblioteket NumPy

### vektor med 6 element

In [ ]:
import numpy as np
x1 = np.array([1, 2, 3, 4, 5, 6])
print(x1.shape)
print(x1.ndim)
x1

(6,)
1


array([1, 2, 3, 4, 5, 6])

In [ ]:
# index börjar på 0
x1[0]

1

In [ ]:
x1[3]

4

In [ ]:
x1[-1]

6

### matris med 2 rader och 3 kolumner

In [ ]:
x2 = np.array([[1, 2, 3], [4, 5, 6]])
print(x2.shape)
print(x2.ndim)
x2

(2, 3)
2


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x2[1, 2]

6

### slicing

In [ ]:
# från index 3 och framåt
x1[3:]

array([4, 5, 6])

In [ ]:
# från start och till och med index 2
x1[:3]

array([1, 2, 3])

In [ ]:
x2[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# första raden, alla kolumner
x2[:1, :]

array([[1, 2, 3]])

In [ ]:
# alla rader, sista kolumnen
x2[:, -1]

array([3, 6])